import crypto from 'node:crypto';
import { config } from '@/core/config.js';

const ALGORITHM = 'aes-256-gcm';
// Using a 32-byte key derived from JWT_ACCESS_SECRET or fallback
const RAW_KEY = config.JWT_ACCESS_SECRET || '0123456789abcdef0123456789abcdef'; 
const ENCRYPTION_KEY = crypto.scryptSync(RAW_KEY, 'salt', 32);

/**
 * AES-256-GCM authenticated encryption service.
 * Used for field-level encryption of highly sensitive PII data at rest.
 */
export class EncryptionService {
  /**
   * Encrypts a plaintext string and returns a base64 encoded payload
   * containing the IV, auth tag, and encrypted data.
   */
  static encrypt(text: string): string {
    if (!text) return text;
    try {
      const iv = crypto.randomBytes(16);
      const cipher = crypto.createCipheriv(ALGORITHM, ENCRYPTION_KEY, iv);
      let encrypted = cipher.update(text, 'utf8', 'base64');
      encrypted += cipher.final('base64');
      const authTag = cipher.getAuthTag().toString('base64');
      const ivStr = iv.toString('base64');
      
      // Format: iv:authTag:encryptedData
      return `${ivStr}:${authTag}:${encrypted}`;
    } catch (error) {
      console.error('Encryption failed:', error);
      throw new Error('Encryption failed');
    }
  }

  /**
   * Decrypts a payload previously generated by encrypt().
   */
  static decrypt(payload: string): string {
    if (!payload || !payload.includes(':')) return payload;
    try {
      const [ivStr, authTagStr, encrypted] = payload.split(':');
      if (!ivStr || !authTagStr || !encrypted) return payload; // Fallback for unencrypted legacy data

      const iv = Buffer.from(ivStr, 'base64');
      const authTag = Buffer.from(authTagStr, 'base64');
      
      const decipher = crypto.createDecipheriv(ALGORITHM, ENCRYPTION_KEY, iv);
      decipher.setAuthTag(authTag);
      
      let decrypted = decipher.update(encrypted, 'base64', 'utf8');
      decrypted += decipher.final('utf8');
      
      return decrypted;
    } catch (error) {
      console.error('Decryption failed for payload. It may be corrupted or key changed.');
      return ''; // Do not leak info
    }
  }
}
