/**
 * All application-level error codes.
 *
 * Design: Error codes are namespaced by domain prefix. This makes errors
 * machine-parseable by clients and enables precise error handling without
 * string matching on messages (which change; codes don't).
 *
 * Format: DOMAIN_SPECIFIC_ERROR
 */
export const ErrorCode = {
  // ── Generic ─────────────────────────────────────────────────────────
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

  // ── Authentication ───────────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_NOT_FOUND: "AUTH_ACCOUNT_NOT_FOUND",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_ACCOUNT_UNVERIFIED: "AUTH_ACCOUNT_UNVERIFIED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_MFA_TOKEN_INVALID: "AUTH_MFA_TOKEN_INVALID",
  AUTH_OAUTH_FAILED: "AUTH_OAUTH_FAILED",
  AUTH_OAUTH_EMAIL_EXISTS: "AUTH_OAUTH_EMAIL_EXISTS",
  AUTH_PASSWORD_TOO_WEAK: "AUTH_PASSWORD_TOO_WEAK",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_USERNAME_ALREADY_EXISTS: "AUTH_USERNAME_ALREADY_EXISTS",
  AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",
  AUTH_ROLE_MISMATCH: "AUTH_ROLE_MISMATCH",

  // ── User ────────────────────────────────────────────────────────────
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",

  // ── Company ─────────────────────────────────────────────────────────
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_ALREADY_EXISTS: "COMPANY_ALREADY_EXISTS",
  COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
  COMPANY_QUOTA_EXCEEDED: "COMPANY_QUOTA_EXCEEDED",
  COMPANY_NOT_OWNER: "COMPANY_NOT_OWNER",
  COMPANY_MEMBER_NOT_FOUND: "COMPANY_MEMBER_NOT_FOUND",
  COMPANY_MEMBER_ALREADY_EXISTS: "COMPANY_MEMBER_ALREADY_EXISTS",
  COMPANY_CANNOT_REMOVE_OWNER: "COMPANY_CANNOT_REMOVE_OWNER",

  // ── Candidate ───────────────────────────────────────────────────────
  CANDIDATE_NOT_FOUND: "CANDIDATE_NOT_FOUND",
  CANDIDATE_PROFILE_INCOMPLETE: "CANDIDATE_PROFILE_INCOMPLETE",

  // ── Trial ────────────────────────────────────────────────────────────
  TRIAL_NOT_FOUND: "TRIAL_NOT_FOUND",
  TRIAL_NOT_PUBLISHED: "TRIAL_NOT_PUBLISHED",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",
  TRIAL_ALREADY_SUBMITTED: "TRIAL_ALREADY_SUBMITTED",
  TRIAL_SUBMISSION_NOT_FOUND: "TRIAL_SUBMISSION_NOT_FOUND",
  TRIAL_SUBMISSION_EXPIRED: "TRIAL_SUBMISSION_EXPIRED",
  TRIAL_NOT_IN_PROGRESS: "TRIAL_NOT_IN_PROGRESS",

  // ── Evaluation ───────────────────────────────────────────────────────
  EVALUATION_NOT_FOUND: "EVALUATION_NOT_FOUND",
  EVALUATION_ALREADY_EXISTS: "EVALUATION_ALREADY_EXISTS",
  EVALUATION_PROCESSING: "EVALUATION_PROCESSING",
  EVALUATION_PROVIDER_UNAVAILABLE: "EVALUATION_PROVIDER_UNAVAILABLE",

  // ── Pipeline ────────────────────────────────────────────────────────
  PIPELINE_NOT_FOUND: "PIPELINE_NOT_FOUND",
  PIPELINE_STAGE_NOT_FOUND: "PIPELINE_STAGE_NOT_FOUND",
  PIPELINE_INVALID_TRANSITION: "PIPELINE_INVALID_TRANSITION",

  // ── Storage ─────────────────────────────────────────────────────────
  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  STORAGE_FILE_NOT_FOUND: "STORAGE_FILE_NOT_FOUND",
  STORAGE_INVALID_FILE_TYPE: "STORAGE_INVALID_FILE_TYPE",
  STORAGE_FILE_TOO_LARGE: "STORAGE_FILE_TOO_LARGE",
  STORAGE_SIGNED_URL_FAILED: "STORAGE_SIGNED_URL_FAILED",

  // ── AI Gateway ──────────────────────────────────────────────────────
  AI_ALL_PROVIDERS_FAILED: "AI_ALL_PROVIDERS_FAILED",
  AI_PROVIDER_RATE_LIMITED: "AI_PROVIDER_RATE_LIMITED",
  AI_SAFETY_VIOLATION: "AI_SAFETY_VIOLATION",
  AI_PROMPT_NOT_FOUND: "AI_PROMPT_NOT_FOUND",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",

  // ── Assessment ──────────────────────────────────────────────────────
  ASSESSMENT_NOT_FOUND: "ASSESSMENT_NOT_FOUND",
  ASSESSMENT_NOT_PUBLISHED: "ASSESSMENT_NOT_PUBLISHED",
  ASSESSMENT_EXPIRED: "ASSESSMENT_EXPIRED",
  ASSESSMENT_ALREADY_SUBMITTED: "ASSESSMENT_ALREADY_SUBMITTED",
  ASSESSMENT_NOT_IN_PROGRESS: "ASSESSMENT_NOT_IN_PROGRESS",

  // ── Queue ────────────────────────────────────────────────────────────
  QUEUE_JOB_FAILED: "QUEUE_JOB_FAILED",
  QUEUE_JOB_NOT_FOUND: "QUEUE_JOB_NOT_FOUND",

  // ── Notification ─────────────────────────────────────────────────────
  NOTIFICATION_SEND_FAILED: "NOTIFICATION_SEND_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
